// <auto-generated />
using System;
using Kestrelle.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kestrelle.Models.Migrations
{
    [DbContext(typeof(KestrelleDbContext))]
    partial class KestrelleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kestrelle")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kestrelle.Models.Entities.DiscordGuild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Guilds", "kestrelle");
                });

            modelBuilder.Entity("Kestrelle.Models.Entities.DiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Users", "kestrelle");
                });

            modelBuilder.Entity("Kestrelle.Models.Entities.Sound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsPublicWithinGuild")
                        .HasColumnType("boolean");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("integer");

                    b.Property<decimal>("UploadedByUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("GuildId", "DisplayName");

                    b.ToTable("Sounds", "kestrelle");
                });

            modelBuilder.Entity("Kestrelle.Models.Entities.Sound", b =>
                {
                    b.HasOne("Kestrelle.Models.Entities.DiscordGuild", "Guild")
                        .WithMany("Sounds")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kestrelle.Models.Entities.DiscordUser", "UploadedByUser")
                        .WithMany("UploadedSounds")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Kestrelle.Models.Entities.DiscordGuild", b =>
                {
                    b.Navigation("Sounds");
                });

            modelBuilder.Entity("Kestrelle.Models.Entities.DiscordUser", b =>
                {
                    b.Navigation("UploadedSounds");
                });
#pragma warning restore 612, 618
        }
    }
}
